### ISSUE TITLE
Deprecated selector in `colorful-dark-syntax\index.less`

### ISSUE THREAD

**Issue by scooterman751** [Keyves/colorful-dark-syntax#1]
In `colorful-dark-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host,
atom-text-editor` => `atom-text-editor,
atom-text-editor`

* `:host .wrap-guide,
atom-text-editor .wrap-guide` => `atom-text-editor .wrap-guide,
atom-text-editor .wrap-guide`

* `:host .indent-guide,
atom-text-editor .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor .indent-guide`

* `:host .invisible-character,
atom-text-editor .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor .invisible-character`

* `:host .gutter,
atom-text-editor .gutter` => `atom-text-editor .gutter,
atom-text-editor .gutter`

* `:host .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line`

* `:host .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `:host .fold-marker:after,
atom-text-editor .fold-marker:after,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number:after,
atom-text-editor .gutter .line-number:after` => `atom-text-editor .fold-marker:after,
atom-text-editor .fold-marker:after,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number:after,
atom-text-editor .gutter .line-number:after`

* `:host .invisible,
atom-text-editor .invisible` => `atom-text-editor .invisible,
atom-text-editor .invisible`

* `:host .cursor,
atom-text-editor .cursor` => `atom-text-editor .cursor,
atom-text-editor .cursor`

* `:host .selection .region,
atom-text-editor .selection .region` => `atom-text-editor .selection .region,
atom-text-editor .selection .region`

* `:host .search-results .marker .region,
atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,
atom-text-editor .search-results .syntax--marker .region`

* `:host .search-results .marker.current-result .region,
atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,
atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.keyword` => `.syntax--keyword`

* `.keyword.control,
.keyword.operator` => `.syntax--keyword.syntax--control,
.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.storage` => `.syntax--storage`

* `.storage.doc` => `.syntax--storage.syntax--doc`

* `.constant` => `.syntax--constant`

* `.constant.boolean,
.constant.null,
.constant.numeric` => `.syntax--constant.syntax--boolean,
.syntax--constant.syntax--null,
.syntax--constant.syntax--numeric`

*

**Comment by cyanql** [comment]
fixed in 0.4.1 😄 , thanks for your issue report
